### ISSUE TITLE
Support all available OpenTopography global raster datasets

### ISSUE THREAD

**Issue by BCampforts** [csdms/bmi-topography#20]
Hi Mark, 

Big fan of bmi-topography here. Would it be feasible to support NASADEM and copernicus as well? 
See: https://opentopography.org/news/nasadem-and-copernicus-dem

Benjamin

**Comment by mdpiper** [comment]
With the addition of API key support in #25, this should be straightforward to add.

**Comment by mdpiper** [comment]
Chris Crosby (the OT PI at UNAVCO!) requested we support all global raster datasets available through the OT API, including:
* SRTM15Plus (Global Bathymetry SRTM15+ V2.1)
* NASADEM (NASADEM Global DEM)
* COP30 (Copernicus Global DSM 30m)
* COP90 (Copernicus Global DSM 90m)
