### ISSUE TITLE
Fix documentation build

### ISSUE THREAD

**Issue by mdpiper** [csdms/bmi-topography#61]
Previously, I had been using *pandoc* to translate the Markdown files in the root directory of the repository into *sphinx*-friendly reStructuredText files for the documentation. In the move to *nox* for managing automated tasks, this got lost. It's now breaking. I need to evaluate if this workflow is still needed and fix it.

**Comment by mcflugen** [comment]
I think [myst-parser](https://pypi.org/project/myst-parser/) sphinx extension should do the trick.

**Comment by mdpiper** [comment]
Ah, that would be awesome!

**Comment by mdpiper** [comment]
Pretty sure this is caused by the md/rst formatting in the changelog when it's updated by *zest.releaser*. Converting to MyST for the docs should fix this.

**Comment by mdpiper** [comment]
Fixedf with #68.
